/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ["class"],
  content: [
    "./pages/**/*.{js,jsx,ts,tsx}",
    "./components/**/*.{js,jsx,ts,tsx}",
    "./app/**/*.{js,jsx,ts,tsx}",
    "./src/**/*.{js,jsx,ts,tsx}",
  ],
  safelist: [
    "bg-stone-200",
    "text-stone-500",
    "text-emerald-500",
    "bg-emerald-200",
    "bg-sky-500",
    "text-sky-500",
    "bg-sky-200",
    "bg-violet-200",
    "text-violet-500",
    "bg-rose-500",
    "text-rose-500",
    "bg-lime-500",
    "text-lime-500",
    "bg-teal-500",
    "text-teal-500",
    "bg-amber-500",
    "bg-amber-200",
    "bg-orange-500",
    "bg-orange-200",
    "text-orange-500",
    "bg-purple-500",
    "bg-purple-300",
    "bg-purple-200",
    "text-purple-500",
    "bg-blue-500",
    "bg-blue-300",
    "bg-blue-200",
    "text-blue-500",
    "bg-green-500",
    "bg-green-200",
    "text-green-500",
    "text-green-400",
    "bg-green-400",
    "bg-green-200",
    "bg-gray-300",
    "bg-gray-200",
    "text-gray-500",
    "text-gray-300",
    "bg-red-500",
    "bg-red-200",
    "text-red-500",
  ],
  prefix: "",
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
};
