export type StepIconMap = {
  [key: string]: string;
};

export const stepIconMap: StepIconMap = {
  // Built-in step icons
  day: "FaSun",
  night: "FaMoon",
  sleep: "GiNightSleep",
  habits: "GiSkills",

  // Existing custom steps
  confidence: "GiAura",
  awareness: "GiAwareness",
  positivity: "GiHealing",
  resilience: "GiGuardedTower",
  highlights: "FaStar",
  overview: "GiPencilRuler",
  bonus: "FaBoltLightning",
  default: "GiInnerSelf",

  discipline: "GiSurroundedShield",
  gratitude: "GiBeamsAura",
  wisdom: "GiSmart",
  compassion: "GiHeartInside",
  creativity: "GiTeamIdea",
  courage: "GiLion",
  vitality: "GiHeartBeats",
  purpose: "GiRomanToga",

  gratitudeDepth: "GiBeamsAura", // Radiance of gratitude
  mentalClarity: "GiExtraLucid", // Lucid = clear
  selfCompassion: "GiHealing", // Reused from positivity, fits compassion
  delayedGratification: "GiSpikedWall", // Boundary, resistance
  integrity: "GiRomanToga", // Symbol of principle/integrity
  happiness: "GiIciclesAura", // Radiating positivity
  mentalFlexibility: "GiDuality", // Two sides/viewpoints
  concentration: "GiMeditation", // Calm, focus
  lettingGo: "GiTeleport", // Releasing, moving on
};

//JOURNAL STEPS STYLE
export type StepStyle = {
  bgColor: string;
};

// export const journalStepStyle: { [key: string]: StepStyle } = {
//   default: {
//     bgColor: "bg-journal-day",
//   },
//   bonus: {
//     bgColor: "bg-journal-day",
//   },
//   day: {
//     bgColor: "bg-journal-day",
//   },
//   night: {
//     bgColor: "bg-[linear-gradient(to_right,_#eab308_50%,_#a855f7_50%)]",
//   },
//   sleep: {
//       bgColor: "bg-journal-sleep",
//   },
//   highlights: {
//     bgColor: "bg-journal-night",
//   },
//   habits: {
//     bgColor: "bg-habit-main",
//   },
//   dayEntry: {
//     bgColor: "bg-journal-day",
//   },
//   nightEntry: {
//     bgColor: "bg-journal-night",
//   },
// };

// export const getJournalStepStyle = (stepType: string): StepStyle => {
//   return journalStepStyle[stepType] || journalStepStyle.default;
// };

export const getStepBgColor = (stepType: string): string => {
  if (stepType === "night") return "bg-[linear-gradient(to_right,var(--journal-day)_50%,var(--journal-night)_50%)]";
  if (stepType === "nightEntry" || stepType === "highlights") return "bg-journal-night";
  if (stepType === "habits") return "bg-habit-main";
  if (stepType === "sleep") return "bg-journal-sleep";
  return "bg-journal-day";
};

export function getTimePeriodIconAndColor(
  timePeriod: "day" | "night" | "sleep"
) {
  switch (timePeriod) {
    case "day":
      return {
        periodColor: "journal-day",
        iconName: stepIconMap.day,
      };
    case "night":
      return {
        periodColor: "journal-night",
        iconName: stepIconMap.night,
      };
    default: // 'sleep'
      return {
        periodColor: "journal-sleep",
        iconName: stepIconMap.sleep,
      };
  }
}

export const PRACTICE_ICON_CATEGORIES: { [category: string]: string[] } = {
  "Mind & Focus": [
    "GiMeditation",
    "GiBrain",
    "GiAwareness",
    "GiInnerSelf",
    "GiExtraLucid",
    "GiDuality",
    "GiPsychicWaves",
    "GiThink",
    "GiAura",
    "GiBeamsAura",
    "GiIciclesAura",
    "GiRearAura",
    "GiTelepathy",
    "GiBrainstorm",
    "GiWisdom",
    "GiEnlightenment",
    "GiThirdEye",
    "GiAllSeeingEye",
    "GiEyeOfHorus",
    "GiSemiClosedEye",
    "GiDreamCatcher",
    "GiHiveMind",
    "GiConcentrationOrb",
    "GiFocusedLightning",
    "GiSparkSpirit",
    "GiSleepy",
    "GiBookAura",
    "GiIdea",
    "GiDualityMask",
    "GiCrystalEye",
  ],
  "Body & Health": [
    "GiMuscleUp",
    "GiBiceps",
    "GiHeartBeats",
    "GiRun",
    "GiRunningShoe",
    "GiWalk",
    "GiNightSleep",
    "GiBed",
    "GiHealthIncrease",
    "GiWeightLiftingUp",
    "GiMeal",
    "GiShinyApple",
    "GiWaterDrop",
    "GiStrong",
    "GiHealing",
    "GiStrongMan",
    "GiBodyBalance",
    "GiFist",
    "GiFootsteps",
    "GiLungs",
    "GiToothbrush",
    "GiShower",
    "GiSoap",
    "GiMedicalPack",
    "GiMedicines",
    "GiPill",
    "GiHealthPotion",
    "GiHerbsBundle",
    "GiCookingPot",
    "GiHotMeal",
    "GiEating",
    "GiFruitBowl",
    "GiWaterBottle",
    "GiCoffeeCup",
    "GiTeapotLeaves",
    "GiMilkCarton",
    "GiBreadSlice",
    "GiCheeseWedge",
    "GiWeightScale",
    "GiPersonInBed",
    "GiPillow",
    "GiSleepingBag",
    "GiBattery100",
    "GiKiwiFruit",
    "GiWatermelon",
  ],
  "Learning & Knowledge": [
    "GiWhiteBook",
    "GiOpenBook",
    "GiBookshelf",
    "GiRead",
    "GiOwl",
    "GiGraduateCap",
    "GiNotebook",
    "GiPencil",
    "GiScrollUnfurled",
    "GiGiftOfKnowledge",
    "GiClassicalKnowledge",
    "GiSpellBook",
    "GiSmart",
    "GiSkills",
    "GiBlackBook",
    "GiBookCover",
    "GiBookPile",
    "GiBookStorm",
    "GiBookmark",
    "GiSecretBook",
    "GiRuleBook",
    "GiTeacher",
    "GiAbacus",
    "GiAtom",
    "GiMaterialsScience",
    "GiMagnifyingGlass",
    "GiArchiveResearch",
    "GiGlobe",
    "GiCompass",
    "GiTreasureMap",
    "GiFoldedPaper",
    "GiNewspaper",
    "GiPaperPlane",
    "GiPencilRuler",
    "GiQuill",
    "GiQuillInk",
    "GiScrollQuill",
    "GiTiedScroll",
    "GiTestTubes",
    "GiFizzingFlask",
    "GiTinker",
    "GiAnatomy",
  ],
  "Creativity & Craft": [
    "GiPaintBrush",
    "GiMusicalNotes",
    "GiGuitar",
    "GiDrum",
    "GiSing",
    "GiTheaterCurtains",
    "GiAnvilImpact",
    "GiCrafting",
    "GiPhotoCamera",
    "GiPaintedPottery",
    "GiLargePaintBrush",
    "GiPaintBucket",
    "GiPaintRoller",
    "GiPalette",
    "GiPencilBrush",
    "GiMusicalScore",
    "GiMusicalKeyboard",
    "GiPianoKeys",
    "GiGrandPiano",
    "GiGuitarHead",
    "GiDrumKit",
    "GiViolin",
    "GiHarp",
    "GiTrumpet",
    "GiDramaMasks",
    "GiTheater",
    "GiFilmProjector",
    "GiFilmSpool",
    "GiVideoCamera",
    "GiSparkles",
    "GiMagicHat",
    "GiMagickTrick",
    "GiMagicSwirl",
    "GiPartyPopper",
    "GiSewingMachine",
    "GiSewingNeedle",
    "GiStoneCrafting",
    "GiAnvil",
    "GiHammerNails",
    "GiInkSwirl",
    "GiPartyHat",
    "GiCartwheel",
    "GiMusicSpell",
  ],
  "People & Kindness": [
    "GiHearts",
    "GiHeartInside",
    "GiLovers",
    "GiThreeFriends",
    "GiTalk",
    "GiConversation",
    "GiShare",
    "GiFamilyHouse",
    "GiCrownedHeart",
    "GiTeamIdea",
    "GiTeamUpgrade",
    "GiTeamDowngrade",
    "GiTwoShadows",
    "GiEternalLove",
    "GiSelfLove",
    "GiRoyalLove",
    "GiLoveLetter",
    "GiLoveSong",
    "GiShiningHeart",
    "GiNestedHearts",
    "GiOppositeHearts",
    "GiHeartWings",
    "GiHeartPlus",
    "GiHeartKey",
    "GiPawHeart",
    "GiChatBubble",
    "GiMeepleGroup",
    "GiPerson",
    "GiShakingHands",
    "GiHandOfGod",
    "GiGloves",
    "GiBabyFace",
    "GiFamilyTree",
    "GiKindle",
    "GiLifeSupport",
    "GiPouringChalice",
    "GiRingingBell",
    "GiDiamondsSmile",
  ],
  "Goals & Discipline": [
    "GiBullseye",
    "GiArcheryTarget",
    "GiOnTarget",
    "GiStairsGoal",
    "GiFlagObjective",
    "GiMountainClimbing",
    "GiTrophy",
    "GiMedal",
    "GiLaurelsTrophy",
    "GiSurroundedShield",
    "GiSwordsEmblem",
    "GiAchievement",
    "GiLion",
    "GiBellShield",
    "GiGuardedTower",
    "GiSwordTie",
    "GiSpikedWall",
    "GiMasterOfArms",
    "GiRomanToga",
    "GiCrown",
    "GiTrophyCup",
    "GiDiamondTrophy",
    "GiSportMedal",
    "GiStarMedal",
    "GiRibbonMedal",
    "GiMedallist",
    "GiTargetArrows",
    "GiTargetShot",
    "GiConvergenceTarget",
    "GiMultipleTargets",
    "GiEyeTarget",
    "GiCheckedShield",
    "GiCrossedSwords",
    "GiSwordInStone",
    "GiSwordAltar",
    "GiMountaintop",
    "GiStairs",
    "GiPathDistance",
    "GiStonePath",
    "GiCheckeredFlag",
    "GiLevelEndFlag",
    "GiLaurelCrown",
    "GiCrownCoin",
    "GiPodiumWinner",
    "GiTargetPrize",
  ],
  "Nature & Calm": [
    "GiPineTree",
    "GiOakLeaf",
    "GiFlowerTwirl",
    "GiSeedling",
    "GiLotusFlower",
    "GiWaves",
    "GiFlame",
    "GiSunflower",
    "GiSunrise",
    "GiSunset",
    "GiStoneStack",
    "GiWhirlwind",
    "GiSun",
    "GiMoon",
    "GiSunbeams",
    "GiSunCloud",
    "GiMoonOrbit",
    "GiNightSky",
    "GiStarsStack",
    "GiFallingStar",
    "GiRainbowStar",
    "GiRaining",
    "GiSnowflake1",
    "GiRiver",
    "GiWaterfall",
    "GiSeaTurtle",
    "GiSeagull",
    "GiDove",
    "GiPeaceDove",
    "GiFreedomDove",
    "GiHummingbird",
    "GiButterfly",
    "GiCat",
    "GiSittingDog",
    "GiRabbit",
    "GiDeer",
    "GiFox",
    "GiHorseHead",
    "GiBee",
    "GiRose",
    "GiFlowers",
    "GiDandelionFlower",
    "GiFallingLeaf",
    "GiMapleLeaf",
    "GiPlantSeed",
    "GiCampfire",
    "GiMountains",
  ],
  "Time & Routine": [
    "GiHourglass",
    "GiSandsOfTime",
    "GiAlarmClock",
    "GiStopwatch",
    "GiCalendar",
    "GiPocketWatch",
    "GiSundial",
    "GiClockwiseRotation",
    "GiPlayerTime",
    "GiEmptyHourglass",
    "GiWatch",
    "GiCuckooClock",
    "GiRingingAlarm",
    "GiClockwork",
    "GiAnticlockwiseRotation",
    "GiBackwardTime",
    "GiExtraTime",
    "GiHeavyTimer",
    "GiTimeSynchronization",
    "GiSolarTime",
    "GiCycle",
    "GiRecycle",
    "GiStarCycle",
    "GiCalendarHalfYear",
    "GiAztecCalendarSun",
  ],
};
